import express from "express";
const router = express.Router();
import { postController, uploadImageController } from "../controller";
// import { createPost } from "../controller/postController";
// router.get("/", postController.testing);
router.post("/createPost", postController.createPost);
router.get("/posts", postController.readPost);
router.get("/posts/:id", postController.readPost);
router.post("/file/upload", uploadImageController.uploadImage);
router.post("/updateposts/:id", postController.updatePost);
router.delete("/posts/:id", postController.deletePost);
export default router;
